### ISSUE TITLE
Is there a way to make the components behind the circle to be clickable ??

### ISSUE THREAD

**Issue by mannycolon** [MatisLepik/react-spotlight#1]
Good job with this component !!

**Comment by MatisLepik** [comment]
Hey,

Your best bet is probably to set `pointer-events: none;` on the outer wrapper. Although then you can also click through the backdrop. I'm not sure if there's a better solution.

Regardless, 1.1.0 is released which lets you pass in `outerStyles` and `innerStyles` properties, which might help with this.

**Comment by mannycolon** [comment]
awesome thank you
